local Code = {
    "Sub2Fer999",
    "Enyo_is_Pro",
    "Magicbus",
    "JCWK",
    "Starcodeheo",
    "Bluxxy",
    "fudd10_v2",
    "3BVISITS",
    "UPD16",
    "FUDD10",
    "BIGNEWS",
    "Sub2OfficialNoobie",
    "SUB2GAMERROBOT_EXP1",
    "StrawHatMaine",
    "SUB2NOOBMASTER123",
    "Sub2Daigrock",
    "Axiore",
    "TantaiGaming",
    "STRAWHATMAINE",
}
return Code
